// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB565vVLsWBsiDfpE_e7eVfCR5bZeIFI4',
    appId: '1:1083982042503:web:9bc8ad092ea2c76eca6f22',
    messagingSenderId: '1083982042503',
    projectId: 'helloworld-87567',
    authDomain: 'helloworld-87567.firebaseapp.com',
    storageBucket: 'helloworld-87567.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd61YRoAyrO7VkipkbvkEOe3TCO-cBFUI',
    appId: '1:1083982042503:android:ccfe714bb21505dfca6f22',
    messagingSenderId: '1083982042503',
    projectId: 'helloworld-87567',
    storageBucket: 'helloworld-87567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xKufCwkKdjjTEPFl6N-R5NOFjrq3uzs',
    appId: '1:1083982042503:ios:9de39201b54940d1ca6f22',
    messagingSenderId: '1083982042503',
    projectId: 'helloworld-87567',
    storageBucket: 'helloworld-87567.firebasestorage.app',
    iosBundleId: 'com.example.bandekar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xKufCwkKdjjTEPFl6N-R5NOFjrq3uzs',
    appId: '1:1083982042503:ios:9de39201b54940d1ca6f22',
    messagingSenderId: '1083982042503',
    projectId: 'helloworld-87567',
    storageBucket: 'helloworld-87567.firebasestorage.app',
    iosBundleId: 'com.example.bandekar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB565vVLsWBsiDfpE_e7eVfCR5bZeIFI4',
    appId: '1:1083982042503:web:cf14f3419bd88b83ca6f22',
    messagingSenderId: '1083982042503',
    projectId: 'helloworld-87567',
    authDomain: 'helloworld-87567.firebaseapp.com',
    storageBucket: 'helloworld-87567.firebasestorage.app',
  );
}
